apiVersion: v1
kind: Namespace
metadata:
  name: genai-toolbox
  labels:
    kubernetes.io/metadata.name: genai-toolbox
    opendatahub.io/dashboard: "true"
    app.kubernetes.io/name: genai-toolbox
    app.kubernetes.io/part-of: genai-toolbox
