apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: orchestrator-role
  namespace: orchestrator-rhoai
  labels:
    app.kubernetes.io/name: orchestrator-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: orchestrator-rhoai
rules:
  - apiGroups: [""]
    resources: [secrets, configmaps, services]
    verbs: [get, list, watch]
  - apiGroups: [serving.kserve.io]
    resources: [inferenceservices]
    verbs: [get, list, watch]
