apiVersion: v1
kind: ServiceAccount
metadata:
  name: orchestrator-sa
  namespace: orchestrator-rhoai
  labels:
    app.kubernetes.io/name: orchestrator-sa
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: orchestrator-rhoai
