apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: llamastack

resources:
  - llama-stack-secret.yaml
  - gemini-secret.yaml
  - llamastack-custom-config.yaml
  - llamastack-distribution.yaml
