apiVersion: llamastack.io/v1alpha1
kind: LlamaStackDistribution
metadata:
  name: llamastack
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 1
  server:
    distribution:
      name: rh-dev
    userConfig:
      configMapName: llamastack-custom-config
    containerSpec:
      name: llama-stack
      port: 8321
      resources:
        requests:
          cpu: 250m
          memory: 500Mi
        limits:
          cpu: "4"
          memory: 12Gi
      env:
        - name: POSTGRES_HOST
          value: postgres.llamastack.svc.cluster.local
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          value: llamastack
        - name: POSTGRES_USER
          value: llamastack
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: INFERENCE_MODEL
          valueFrom:
            secretKeyRef:
              name: llama-stack-secret
              key: INFERENCE_MODEL
        - name: VLLM_URL
          valueFrom:
            secretKeyRef:
              name: llama-stack-secret
              key: VLLM_URL
        - name: VLLM_TLS_VERIFY
          valueFrom:
            secretKeyRef:
              name: llama-stack-secret
              key: VLLM_TLS_VERIFY
        - name: VLLM_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: llama-stack-secret
              key: VLLM_API_TOKEN
        - name: VLLM_MAX_TOKENS
          valueFrom:
            secretKeyRef:
              name: llama-stack-secret
              key: VLLM_MAX_TOKENS
        - name: ENABLE_FAISS
          value: "faiss"
        - name: EMBEDDING_MODEL
          valueFrom:
            secretKeyRef:
              name: llama-stack-secret
              key: EMBEDDING_MODEL
        - name: EMBEDDING_PROVIDER_MODEL_ID
          valueFrom:
            secretKeyRef:
              name: llama-stack-secret
              key: EMBEDDING_PROVIDER_MODEL_ID
        - name: VLLM_EMBEDDING_URL
          valueFrom:
            secretKeyRef:
              name: llama-stack-secret
              key: VLLM_EMBEDDING_URL
        - name: VLLM_EMBEDDING_TLS_VERIFY
          valueFrom:
            secretKeyRef:
              name: llama-stack-secret
              key: VLLM_EMBEDDING_TLS_VERIFY
        - name: VLLM_EMBEDDING_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: llama-stack-secret
              key: VLLM_EMBEDDING_API_TOKEN
        - name: VLLM_EMBEDDING_MAX_TOKENS
          valueFrom:
            secretKeyRef:
              name: llama-stack-secret
              key: VLLM_EMBEDDING_MAX_TOKENS
        - name: FMS_ORCHESTRATOR_URL
          value: https://guardrails-orchestrator-service.llamastack.svc.cluster.local:8032
        - name: FMS_VERIFY_SSL
          value: "false"
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: gemini-secret
              key: api_key
    storage:
      size: 5Gi
  network:
    exposeRoute: true
