apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - okp-access-secret.yaml
  - solr-pvc.yaml
  - solr-deployment.yaml
  - solr-service.yaml
  - mcp-deployment.yaml
  - mcp-service.yaml
  - mcp-route.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: rhokp
