apiVersion: v1
kind: Secret
metadata:
  name: okp-access-secret
  labels:
    app.kubernetes.io/name: rhokp
    app.kubernetes.io/component: config
  annotations:
    description: >-
      OKP access key for the Solr index.
      Update OKP_ACCESS_KEY for your environment.
type: Opaque
stringData:
  OKP_ACCESS_KEY: CHANGE_ME
