apiVersion: v1
kind: Namespace
metadata:
  name: llamastack
  labels:
    kubernetes.io/metadata.name: llamastack
    opendatahub.io/dashboard: "true"
    app.kubernetes.io/name: llamastack
    app.kubernetes.io/part-of: llamastack
