apiVersion: v1
kind: ServiceAccount
metadata:
  name: genai-toolbox-sa
  labels:
    app.kubernetes.io/name: genai-toolbox-sa
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: genai-toolbox
