apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: orchestrator-8b

labels:
  - pairs:
      app.kubernetes.io/part-of: orchestrator-8b

resources:
  - namespace.yaml
  - pvc.yaml
  - download-job.yaml
  - serving-runtime.yaml
  - inference-service.yaml
  - service.yaml
  - route.yaml

images:
  - name: registry.redhat.io/rhaiis/vllm-cuda-rhel9
    newTag: "3.4.0"
