apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: qwen-math-7b

labels:
  - pairs:
      app.kubernetes.io/part-of: qwen-math-7b
      tier: "1"

resources:
  - ../../manifests
