apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: orchestrator-8b

labels:
  - pairs:
      app.kubernetes.io/part-of: orchestrator-8b
      tier: "1"

resources:
  - ../../manifests
