apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: orchestrator-rhoai

labels:
  - pairs:
      app.kubernetes.io/part-of: orchestrator-rhoai

resources:
  - namespace.yaml
  - rbac/
  - config/
  - network/
