apiVersion: v1
kind: Namespace
metadata:
  name: orchestrator-rhoai
  labels:
    kubernetes.io/metadata.name: orchestrator-rhoai
    opendatahub.io/dashboard: "true"
    app.kubernetes.io/name: orchestrator-rhoai
    app.kubernetes.io/part-of: orchestrator-rhoai
