apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../projects/usecases-project.yaml
  - cluster-models-appset.yaml
  - cluster-services-appset.yaml
  - training-workloads-app.yaml
