apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: usecase-toolorchestra-training
  namespace: openshift-gitops
spec:
  project: usecases
  source:
    repoURL: https://github.com/rrbanda/rhoai-usecases.git
    targetRevision: main
    path: usecases/services/toolorchestra-app/manifests/training/workloads
  destination:
    server: https://kubernetes.default.svc
    namespace: orchestrator-rhoai
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 30s
        maxDuration: 5m0s
        factor: 2
