apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: orchestrator-rhoai

labels:
  - pairs:
      app.kubernetes.io/part-of: orchestrator-rhoai

resources:
  - orchestrator-ui-code-configmap.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml
