apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: orchestrator-ui
  namespace: orchestrator-rhoai
  labels:
    app.kubernetes.io/name: orchestrator-ui
    app.kubernetes.io/component: ui
    app.kubernetes.io/part-of: orchestrator-rhoai
  annotations:
    haproxy.router.openshift.io/timeout: 5m
spec:
  to:
    kind: Service
    name: orchestrator-ui
  port:
    targetPort: 7860
  tls:
    termination: edge
  wildcardPolicy: None
