apiVersion: v1
kind: Service
metadata:
  name: orchestrator-ui
  namespace: orchestrator-rhoai
  labels:
    app.kubernetes.io/name: orchestrator-ui
    app.kubernetes.io/component: ui
    app.kubernetes.io/part-of: orchestrator-rhoai
spec:
  selector:
    app.kubernetes.io/name: orchestrator-ui
  ports:
    - port: 7860
      targetPort: 7860
      protocol: TCP
      name: http
