apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: genai-toolbox

labels:
  - pairs:
      app.kubernetes.io/part-of: genai-toolbox
      tier: "1"

resources:
  - ../../manifests/base
  - ../../manifests/server
